### ISSUE TITLE
Could you please give exact package version in the requirements?

### ISSUE THREAD

**Issue by LTTeddie** [Eydcao/BSMS-GNN#3]

**Comment by Eydcao** [comment]
Hi Dear LTTeddie,

Unfortunately, I lost the virtual environment previously because of a re-installing so I cannot give you the detailed versions.

But, 1) I still remember the only problem is scipy, as in the latest version they deprecate some sparse matrix operations. This is only used in generating the multi-level (one pass). So I used pip to install an older version before the deprecate happened.

2) could you try to use Conda and default versions for every library and show if there are any problems? If you can provide the detailed errors. I may also try to fix it.

Best,
Yadi

**Comment by noor-malaika** [comment]
torch==2.0.1
torch-geometric==2.3.1
numpy==1.24.3
h5py==3.8.0
tensorboard==2.13.0
scipy==1.14.0
scikit-learn==1.2.2
sparse-dot-mkl==0.8.0




    from sparse_dot_mkl._mkl_interface import (MKL, sparse_matrix_t, _create_mkl_sparse, debug_print, debug_timer,
  File "/home/sces55/.local/share/virtualenvs/BSMS-GNN-6Qp8n7Qn/lib/python3.10/site-packages/sparse_dot_mkl/_mkl_interface/__init__.py", line 65, in <module>
    _empirical_set_dtype()
  File "/home/sces55/.local/share/virtualenvs/BSMS-GNN-6Qp8n7Qn/lib/python3.10/site-packages/sparse_dot_mkl/_mkl_interface/__init__.py", line 53, in _empirical_set_dtype
    _validate_dtype()
  File "/home/sces55/.local/share/virtualenvs/BSMS-GNN-6Qp8n7Qn/lib/python3.10/site-packages/sparse_dot_mkl/_mkl_interface/__init__.py", line 29, in _validate_dtype
    test_comparison = test_array.A
AttributeError: 'csc_matrix' object has no attribute 'A'


These are my versions and the error that is thrown, can u recommend the old version of scipy or any workaround here.
Thanks

**Comment by noor-malaika** [comment]
> torch==2.0.1 torch-geometric==2.3.1 numpy==1.24.3 h5py==3.8.0 tensorboard==2.13.0 scipy==1.14.0 scikit-learn==1.2.2 sparse-dot-mkl==0.8.0
> 
> ```
> from sparse_dot_mkl._mkl_interface import (MKL, sparse_matrix_t, _create_mkl_sparse, debug_print, debug_timer,
> ```
> 
> File "/home/sces55/.local/share/virtualenvs/BSMS-GNN-6Qp8n7Qn/lib/python3.10/site-packages/sparse_dot_mkl/_mkl_interface/**init**.py", line 65, in _empirical_set_dtype() File "/home/sces55/.local/share/virtualenvs/BSMS-GNN-6Qp8n7Qn/lib/python3.10/site-packages/sparse_dot_mkl/_mkl_interface/**init**.py", line 53, in _empirical_set_dtype _validate_dtype() File "/home/sces55/.local/share/virtualenvs/BSMS-GNN-6Qp8n7Qn/lib/python3.10/site-packages/sparse_dot_mkl/_mkl_interface/**init**.py", line 29, in _validate_dtype test_comparison = test_array.A AttributeError: 'csc_matrix' object has no attribute 'A'
> 
> These are my versions and the error that is thrown, can u recommend the old version of scipy or any workaround here. Thanks

@Eydcao

**Comment by Eydcao** [comment]
I am recently updating this repo significantly; It's already in the testing phase

for example, it will soon use poetry to handle all environments. I believe that will resolve all issues.

Best,
yadi

**Comment by noor-malaika** [comment]
> I am recently updating this repo significantly; It's already in the testing phase
> 
> for example, it will soon use poetry to handle all environments. I believe that will resolve all issues.
> 
> Best, yadi

thanks for ur quick response, the issue was due to the use of sparse_dot_mkl, i used scipy's csr_matrix instead of dot_product_mkl and it resolved the issue, i would recommend to avoid dependency issues if u think it'd be better to modify it,
plus i have data for deforming_plate in .tfrec format, while the data structure here is different, so can u provide me the link to datasets already present in h5 format or explain how should i generate h5 files, (e.g., how the group structure should look like),
i tried the link given in ReadMe for data, but there i found a single pre-trained model for plate.
Your help would be appreciated :)

**Comment by Eydcao** [comment]
In the new updates, it will also include the script to translate data
recordings.

But unfortunately due to graduation and the university shrunk my google
drive, I am not sure what currently the link will lead to :(

**Comment by Eydcao** [comment]
Hi the new updates are there as promised;

If you encountered any new issue; let me know by opening a new issue.
