### ISSUE TITLE
Deforming plate

### ISSUE THREAD

**Issue by noor-malaika** [Eydcao/BSMS-GNN#7]
Hi, my work is related to solids, i've tried MeshGraphNets now i want to assess the speed of your implementation,
so far i've resolved some of the issues like the dependency ones but there are a few things that i need to ask, or maybe more if model won't run (i'm using code from ur previous implementation). I would really appreciate if you'd take some time to answer my queries.
Thanks @Eydcao

**Comment by Eydcao** [comment]
Please ask when you encourage a specific problem. Also please constraint the problem to code related only.

For other academic questions, please avoid discussing here but contact me via email.

Note my latest version (Aug/24) no longer support contact cases(as already stated in README) due to my time constraints. But you can implement rather easy with the old commits. Let me know if you would like to do that and PR into my repo, lots of thanks.

But without specific tech questions here, I will close the issue

**Comment by cviviers** [comment]
Hi @Eydcao,

I am trying to re-implement the deforming plate from an old commit. I have it mostly running except for a variable 'normalization_info' that should be coming from the meta.json, but it is not available in the json from deep mind. Do you know where I can get this? 

Thanks in advance.
